# Generated by Django 5.2.13 on 2026-04-25 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_studygroup_teachers_remove_teacher"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Название видеоурока"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "video_file",
                    models.FileField(
                        upload_to="lesson_videos/%Y/%m/%d", verbose_name="Видео файл"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Загружен"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        related_name="video_lessons",
                        to="courses.studygroup",
                        verbose_name="Доступные группы",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_videos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Загрузил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Видеоурок",
                "verbose_name_plural": "Видеоуроки",
                "ordering": ["-created_at"],
            },
        ),
    ]
