# Generated by Django 5.2.13 on 2026-04-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_videolesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("published", "Опубликован"),
                    ("archived", "Архив"),
                ],
                default="published",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
