# Generated by Django 5.2.13 on 2026-04-26 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_lessonattachment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["-scheduled_for", "-created_at"],
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="scheduled_for",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Запланировано на"
            ),
        ),
        migrations.CreateModel(
            name="RecurringLessonPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("physics", "Физика"),
                            ("math", "Математика"),
                            ("cs", "Информатика"),
                        ],
                        max_length=20,
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Понедельник"),
                            (1, "Вторник"),
                            (2, "Среда"),
                            (3, "Четверг"),
                            (4, "Пятница"),
                            (5, "Суббота"),
                            (6, "Воскресенье"),
                        ],
                        verbose_name="День недели",
                    ),
                ),
                ("starts_at", models.TimeField(verbose_name="Время начала")),
                ("start_date", models.DateField(verbose_name="Дата начала расписания")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(verbose_name="Длительность (мин)"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Стоимость (руб)"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание урока"),
                ),
                (
                    "homework",
                    models.TextField(blank=True, verbose_name="Домашнее задание"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_recurring_plans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_plans",
                        to="courses.studygroup",
                        verbose_name="Группа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаблон еженедельного занятия",
                "verbose_name_plural": "Шаблоны еженедельных занятий",
                "ordering": ["weekday", "starts_at"],
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="source_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_lessons",
                to="courses.recurringlessonplan",
                verbose_name="Шаблон расписания",
            ),
        ),
    ]
